version: 0.2

env:
  environment:

  parameter-store:
    image_repo_name: "/${ENVIRONMENT}/image_repo_name"
    task_definition_container_name: "/${ENVIRONMENT}/task_definition_container_name"
    aws_default_region: "/${ENVIRONMENT}/aws_default_region"
    ecs_cluster: "/${ENVIRONMENT}/ecs_cluster"
    ecs_service: "/${ENVIRONMENT}/ecs_service"

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $aws_default_region)
  build:
    commands:
      - docker build -t $image_repo_name .
  post_build:
    commands:
      - docker push $image_repo_name
      - echo "Update ecs service" 
      - aws ecs update-service --cluster $ecs_cluster --service $ecs_service --force-new-deployment --region $aws_default_region
      - printf '[{"name":"%s","imageuri":"%s"}]' $task_definition_container_name  $image_repo_name:$image_tag > imagedefinitions.json 


artifacts:
    files: 
      - imagedefinitions.json
